######################################################################
# Automatically generated by qmake (2.01a) sam. janv. 21 17:28:05 2012
######################################################################

TEMPLATE = app
TARGET = qusbwall 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.hh qusbwall.hh
FORMS += qusbwall.ui
SOURCES += main.cc qusbwall.cc
RESOURCES += toolbar.qrc 
LIBS += -lusbwall
