######################################################################
# Automatically generated by qmake (2.01a) sam. janv. 21 17:28:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.h
FORMS += about.ui qusbwall.ui
SOURCES += main.cpp
RESOURCES += 
LIBS += -lusbwall
